package com.mcu32.firstq.wechat.tools.liufeng.bean;

public class Article {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.id
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.title
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.description
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.picurl
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	private String picurl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.url
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	private String url;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.id
	 * @return  the value of article.id
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.id
	 * @param id  the value for article.id
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.title
	 * @return  the value of article.title
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.title
	 * @param title  the value for article.title
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.description
	 * @return  the value of article.description
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.description
	 * @param description  the value for article.description
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.picurl
	 * @return  the value of article.picurl
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	public String getPicurl() {
		return picurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.picurl
	 * @param picurl  the value for article.picurl
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	public void setPicurl(String picurl) {
		this.picurl = picurl == null ? null : picurl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.url
	 * @return  the value of article.url
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.url
	 * @param url  the value for article.url
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}
}