package com.mcu32.firstq.wechat.tools.liufeng.bean;

public class RrMapping {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rrmapping.id
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rrmapping.requesttype
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	private String requesttype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rrmapping.requestjudgecontent
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	private String requestjudgecontent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rrmapping.responsetype
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	private String responsetype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rrmapping.responseid
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	private String responseid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rrmapping.id
	 * @return  the value of rrmapping.id
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rrmapping.id
	 * @param id  the value for rrmapping.id
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rrmapping.requesttype
	 * @return  the value of rrmapping.requesttype
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	public String getRequesttype() {
		return requesttype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rrmapping.requesttype
	 * @param requesttype  the value for rrmapping.requesttype
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	public void setRequesttype(String requesttype) {
		this.requesttype = requesttype == null ? null : requesttype.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rrmapping.requestjudgecontent
	 * @return  the value of rrmapping.requestjudgecontent
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	public String getRequestjudgecontent() {
		return requestjudgecontent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rrmapping.requestjudgecontent
	 * @param requestjudgecontent  the value for rrmapping.requestjudgecontent
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	public void setRequestjudgecontent(String requestjudgecontent) {
		this.requestjudgecontent = requestjudgecontent == null ? null
				: requestjudgecontent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rrmapping.responsetype
	 * @return  the value of rrmapping.responsetype
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	public String getResponsetype() {
		return responsetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rrmapping.responsetype
	 * @param responsetype  the value for rrmapping.responsetype
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	public void setResponsetype(String responsetype) {
		this.responsetype = responsetype == null ? null : responsetype.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rrmapping.responseid
	 * @return  the value of rrmapping.responseid
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	public String getResponseid() {
		return responseid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rrmapping.responseid
	 * @param responseid  the value for rrmapping.responseid
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	public void setResponseid(String responseid) {
		this.responseid = responseid == null ? null : responseid.trim();
	}
}