package com.mcu32.firstq.wechat.tools.liufeng.bean;

public class Text {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column text.id
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column text.content
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column text.id
	 * @return  the value of text.id
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column text.id
	 * @param id  the value for text.id
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column text.content
	 * @return  the value of text.content
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column text.content
	 * @param content  the value for text.content
	 * @mbggenerated  Thu Jan 02 17:16:12 CST 2014
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}
}